/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoescaños;
 
// import Main.Main ;
// import Placeholder.TextPrompt;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

import java.net.URL; 
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;



public class Login extends javax.swing.JFrame {
   String loginUsuario,passUsuario;
   public static int nivelAccesoLogin;
   boolean f = false;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        TextPrompt txtUsuario= new TextPrompt("Usuario",jTusuario);
        TextPrompt txtContrasenha= new TextPrompt("Contraseña",jPcontrasenha);
        this.setLocationRelativeTo(null);
   //      setIconImage(new ImageIcon(getClass().getResource("../menu/gold.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPcontrasenha = new javax.swing.JPasswordField();
        jBaceptar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        adm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jfondo = new javax.swing.JLabel();
        jPanelinicio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 12)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jTusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTusuarioActionPerformed(evt);
            }
        });
        jPanel3.add(jTusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, -1));

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jPcontrasenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPcontrasenhaActionPerformed(evt);
            }
        });
        jPanel3.add(jPcontrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, -1));

        jBaceptar.setBackground(new java.awt.Color(159, 71, 142));
        jBaceptar.setForeground(new java.awt.Color(255, 255, 255));
        jBaceptar.setText("Aceptar");
        jBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarActionPerformed(evt);
            }
        });
        jPanel3.add(jBaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jBsalir.setBackground(new java.awt.Color(159, 71, 142));
        jBsalir.setForeground(new java.awt.Color(255, 255, 255));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPanel3.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        adm.setBackground(new java.awt.Color(252, 192, 246));
        adm.setText("Administrador");
        adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admActionPerformed(evt);
            }
        });
        jPanel3.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 240));

        jLabel1.setFont(new java.awt.Font("Gotham Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenid@");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cosa 1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 280, 170));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 276, 350));

        Jfondo.setBackground(new java.awt.Color(255, 102, 102));
        Jfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        Jfondo.setText("jLabel1");
        getContentPane().add(Jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));
        getContentPane().add(jPanelinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarActionPerformed
    String u = jTusuario.getText();
    String c = jPcontrasenha.getText(); 
    UsuariosTxt usu = new UsuariosTxt(); 
        if (u.equals("admin") && c.equals("123")) {
            Menu menu = new Menu();
            JOptionPane.showMessageDialog(null, "Bienvenid@");
            menu.show();
        }else{
            JOptionPane.showMessageDialog(null, "Error, verifique los datos");
        }
    }//GEN-LAST:event_jBaceptarActionPerformed

    private void jPcontrasenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPcontrasenhaActionPerformed
    ArrayList<String> lista = new ArrayList();
    FileReader fr = null;
    BufferedReader br;
    try {
        fr = new FileReader("C:Users/adm/Desktop/Proyecto/archivo_usuarios1.txt");
        br = new BufferedReader(fr);
        
        // Lectura del fichero
        String linea;
        while ((linea = br.readLine()) != null) {
            lista.add(linea);
        }
    } catch (IOException e) {
        e.printStackTrace(System.out);
    } finally {
        try {
            if (fr != null) {
                fr.close();
            }
        } catch (IOException e2) {
            e2.printStackTrace(System.out);
        }
    }
        String n = String.join(", ", lista);
        String str[] = n.split("; ");
        String buscar = String.valueOf(jPcontrasenha.getText());
        String g =String.join(",", str);
        String s[] = g.split(",");
 
       boolean no = false;
       boolean val = false;
        for (int i = 0; i < s.length; i++) {
            
            if (s[i].equals(buscar)) {
                no = true;
                System.out.println(s[i-1]);
                if (s[i-1].equals(jTusuario.getText())) {
                 //System.out.println("es su contraseña");
                }
                else if (s[i-1].equals(" "+jTusuario.getText())) {
                 //System.out.println("es su contraseña");
                }else{
                    JOptionPane.showMessageDialog(null, "Correnciales incorrectas");
                }
                System.out.println(s[i+1]);
                if ("0".equals(s[i+1])) {
                    val = true;
                }else{
                    val = false;
                }
            }
           
        }
        if (no==true) {
          System.out.println("digito encontrado");
            
        }else{
            JOptionPane.showMessageDialog(null, "Password no existe");
        }
        
        if (val == true) {
           // System.out.println("es admin");
            f = true;
        }else{
            //System.out.println("no lo es");
             f = false;
        }
        
        

    }//GEN-LAST:event_jPcontrasenhaActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admActionPerformed

    private void jTusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTusuarioActionPerformed
   String cod;
                boolean encontrado = false;
                UsuariosTxt ma = new UsuariosTxt();
                if (!ma.Validarletras(jTusuario.getText().trim())) {
                    JOptionPane.showMessageDialog(null, "Solo acepta letras");

                }else{
                cod = String.valueOf(jTusuario.getText());
                Scanner s;

                try {
                    File f = new File("c:archivo_usuarios1.txt");
                    s = new Scanner(f); int c=0;
                    if (f.exists()) {
                        while (s.hasNextLine() && !encontrado) {
                            String linea = s.nextLine();
                            Scanner sl = new Scanner(linea);

                            sl.useDelimiter("\\s*;\\s*");
                            try {
                                if (cod.equals(String.valueOf(sl.next()))) {
                                   encontrado = true;
                                } else {
                                    encontrado = false;
                                }
                            } catch (Exception e1) {e1.printStackTrace(); }
                        }
                        if (encontrado==false) {JOptionPane.showMessageDialog(null, "no existe");  }
                    }
                    s.close();
                } catch (FileNotFoundException e1) {JOptionPane.showMessageDialog(null, "Error al leer Archivo " + e1); } 
                catch (IOException e1) { e1.printStackTrace();}
            }
    }//GEN-LAST:event_jTusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jfondo;
    private javax.swing.JButton adm;
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelinicio;
    private javax.swing.JPasswordField jPcontrasenha;
    private javax.swing.JTextField jTusuario;
    // End of variables declaration//GEN-END:variables
}
